### ISSUE TITLE
borrow() needs to be sure to root the thing it's borrowing on the stack

### ISSUE THREAD

**Issue by pcwalton** [huonw/boehm-rs#1]
Otherwise LLVM could optimize out the only reference to the object and free it. Bad. Probably it will need to be `.borrow().get()` like `RefCell`.

**Comment by huonw** [comment]
I'm not sure I understand why this is necessary: if you have a `Gc` pointer it is definitely rooted somewhere and when you `.borrow` from it, that freezes that `Gc` in its root, keeping the pointer rooted for (at least) as long as the reference exists.

That said, I would be willing to believe there is in fact some construct with `RefCell`s and `Gc` that lets you remove all roots but keep the borrow... but I can't construct an example.

(By "Otherwise LLVM could optimize out the only reference to the object and free it", do you mean LLVM could remove the one `Gc` pointer, leaving just a `&` reference; or it could optimise out the `&` reference itself?)

**Comment by pcwalton** [comment]
It might be rooted in the unique heap... but oh wait, those will be GC'd too. So never mind, I guess this is not a bug.
